### ISSUE TITLE
Better handling/stack trace for syntax errors

### ISSUE THREAD

**Issue by jayqi** [jayqi/reprexlite#27]
Real syntax errors get gnarly stack traces:

```python
raise SyntaxError("real syntax error")
#> Traceback (most recent call last):
#>   File "/Users/jqi/repos/reprexlite/reprexlite/code.py", line 69, in evaluate
#>     result = eval(str(self).strip(), scope, scope)
#>   File "<string>", line 1
#>     raise SyntaxError("real syntax error")
#>     ^
#> SyntaxError: invalid syntax
#> 
#> During handling of the above exception, another exception occurred:
#> 
#> Traceback (most recent call last):
#>   File "/Users/jqi/repos/reprexlite/reprexlite/code.py", line 71, in evaluate
#>     exec(str(self).strip(), scope, scope)
#>   File "<string>", line 1, in <module>
#>   File "<string>", line None
#> SyntaxError: real syntax error
```

This is because it runs through both the `eval` and `exec` branches and fails both. This can probably be handled more gracefully.

**Comment by jayqi** [comment]
Closed by #72, which also handles real syntax errors that fail at the LibCST parser.
